version: '3.9'
services:
  portrait:
    restart: always
    image: ichiharanaruki/fenics-optimize-academic:latest
    container_name: 'portrait'
    working_dir: '/root/'
    tty: true
    volumes:
    - ../:/workspace
    shm_size: 4gb
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
       - DISPLAY=host.docker.internal:0.0
    environment:
      TZ: 'Asia/Tokyo'
